# This template merge config file lists:
# - patterns: strings to do text substitution on
# - rev_id: a sequential revision id of the template repo (manually maintained for now)
# - required: a full list of all files always merged
# - optional: a full list of all files merged when the --optional flag is used with `gut template`
name = "Keyboard Template"
patterns = ["fin", "fi", "Finnish experiment omorfi"]
rev_id = 3
required = ["und.timestamp",
            "configure.ac",
            "INSTALL",
            "AUTHORS",
            "images/fin-keyboard-menu-icon.png",
            "ios/Fastfile",
            "ios/Matchfile",
            "README",
            "Makefile.am",
            "m4/giella_macros.m4",
            "m4/ax_compare_version.m4",
            "m4/ax_python_module.m4",
            "doc/index.html",
            "doc/layout.html",
            "doc/00README.txt",
            "doc/readme.html",
            "doc/background.png",
            "LICENCE",
            "autogen.sh"]

optional = ["fin.kbdgen/project.yaml",
            "fin.kbdgen/targets/android.yaml",
            "fin.kbdgen/targets/win.yaml",
            "fin.kbdgen/targets/mac.yaml",
            "fin.kbdgen/targets/ios.yaml",
            "fin.kbdgen/resources/mac/readme.html",
            "fin.kbdgen/resources/mac/background.png",
            "fin.kbdgen/resources/mac/icon.fin.png",
            "fin.kbdgen/layouts/fi.yaml",
            "fin.kbdgen/layouts/en.yaml"]

ignored  = []
